[package]
name = "nannou-toys"
version = "0.1.0"
edition = "2021"
description="A set of utilities built on top of Nannou to visualize graphs, etc."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
